name: dotnet Build + Deploy to Docker Hub

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Build the Docker image
        run: docker build -t ombrelin/lasertagtracker:1.0 . --file LaserTagTrackerApi/Dockerfile

      - name: Docker login
        run: echo '${{ secrets.DOCKER_TOKEN }}' | docker login --username ombrelin --password-stdin

      - name: Publish to Docker hub
        run: docker push ombrelin/lasertagtracker:1.0